### PR TITLE
Aurelia fix and removed dependency on JQuery

### PR DESCRIPTION
**Pull request by eric-swann-q2**
Fix for the "Globalized" compatibility issue and also removed dependency to jquery per the suggestion/issue. Also updated a couple of dependencies.

Issue #7 
Issue #8

### CODE REVIEW

**Comment by nevercast** [comment]
What was the close justification? Is this no longer an issue? Did the PR need squashing?

**Comment by eswann** [comment]
They didn't pull this in...no comment.  They haven't been very responsive. If you want a version with this included, feel free to pull from my fork (or just create your own fork and merge in my changes)  
jspm install github:eric-swann-q2/aurelia-material

**Comment by nevercast** [comment]
@eswann Hi Eric, do you lurk on Gitter:Aurelia/Discuss? I addressed @eric-swann-q2 however it seems you're using a different username. Thank you for your reply. I'll use your fork.

**Comment by eswann** [comment]
@nevercast Hey Josh, I don't watch Aurelia/Discuss too often, but yeah I have a personal and work GitHub account...so sometimes on one, sometimes the other :)

**Pull request closed without merging**
